#!/bin/bash
# 
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

export caseName=`basename $PWD`

#We stop this script when we encounter a problem
trap "exit -1" ERR

echo "$caseName: Creating the file blockMeshDict using m4"
pushd constant/polyMesh/ >& /dev/null
m4 -P blockMeshDict.m4 > blockMeshDict
popd

echo "$caseName: Running blockMesh"
runApplication blockMesh

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running addSwirlAndRotation"
runApplication addSwirlAndRotation

echo "$caseName: Running simpleFoam"
runApplication simpleFoam

echo "$caseName: Postprocessing"
cd postProcessing
runApplication sample -case .. -time 1200             
gnuplot compareAll.gplt    >& log.gnuplotCompareAll   
runApplication foamLog ../log.simpleFoam              
gnuplot plotResiduals.gplt >& log.gnuplotPlotResiduals


