#!/bin/bash

if [ -d ECPMixerGgiFvMesh2D_orig ] ; then
     case=ECPMixerGgiFvMesh2D;
else
    echo "sorry, you need to have ECPStitchMesh2D_orig or ECPGgi2D_orig in the current folder";
fi

rm -rf ${case}
rm -rf rotor2D
rm -rf stator2D
rm -rf log.*
