#!/bin/bash
# 
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Load additional RunFunctions 
. ../../tools/RunFunctionsSupplemental

#We stop this script when we encounter a problem
trap "exit -1" ERR

export caseName=`basename $PWD`

echo "$caseName: Creating the file blockMeshDict using m4"
pushd constant/polyMesh/ >& /dev/null
m4 -P blockMeshDict.m4 > blockMeshDict
popd >& /dev/null

echo "$caseName: Running blockMesh"
runApplication blockMesh

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running addSwirlAndRotation"
runApplicationAndReportOnError addSwirlAndRotation

echo "$caseName: Running simpleFoam"
runApplicationAndReportOnError simpleFoam

echo "$caseName: Postprocessing"
cd postProcessing
runApplicationAndReportOnError sample -case .. -time 1000             
runApplicationAndReportOnError gnuplot compareAll.gplt   ; mv log.gnuplot log.gnuplotCompareAll   
runApplicationAndReportOnError foamLog ../log.simpleFoam              
runApplicationAndReportOnError gnuplot plotResiduals.gplt; mv log.gnuplot log.gnuplotPlotResiduals


