#!/bin/bash
# 
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

#We stop this script when we encounter a problem
trap "exit -1" ERR

export caseName=`basename $PWD`

echo "$caseName: Creating the file blockMeshDict using m4"
pushd constant/polyMesh/ >& /dev/null
m4 -P blockMeshDict.m4 > blockMeshDict
popd >& /dev/null

echo "$caseName: Running blockMesh"
runApplication blockMesh

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running addSwirlAndRotation"
runApplication addSwirlAndRotation

echo "$caseName: Running simpleFoam"
runApplication simpleFoam

echo "$caseName: Postprocessing"
cd postProcessing

# Find latest time directory
latestAvailTimeDir=`foamInfoExec -case .. -times | tail -1`

echo "Analysing results for time: $latestAvailTimeDir"

# Run sample
runApplication sample -case .. -latestTime

# Adjust compareAll.gplt: replace "Case1" "??" by "Case1" "$latestAvailTimeDir"
sed -i "s/\"Case1\".*$/\"Case1\" \"$latestAvailTimeDir\"/g" compareAll.gplt

# Run gnuplot to generate the comparison charts
runApplication gnuplot compareAll.gplt   ; mv log.gnuplot log.gnuplotCompareAll

# Run foamLog   
runApplication foamLog ../log.simpleFoam              

# Run gnuplot for the residuals
runApplication gnuplot plotResiduals.gplt; mv log.gnuplot log.gnuplotPlotResiduals


