#!/bin/bash
# 
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Load additional RunFunctions 
. ../../tools/RunFunctionsSupplemental

#We stop this script when we encounter a problem
trap "exit -1" ERR

export caseName=`basename $PWD`

echo "$caseName: Creating the file blockMeshDict using m4"
pushd constant/polyMesh/ >& /dev/null
m4 -P blockMeshDict.m4 > blockMeshDict
popd

echo "$caseName: Running blockMesh"
runApplicationAndReportOnError blockMesh

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running addSwirlAndRotation"
runApplicationAndReportOnError addSwirlAndRotation

echo "$caseName: Running MRFSimpleFoam"
runApplicationAndReportOnError simpleFoam

echo "$caseName: Postprocessing"
cd postProcessing
runApplicationAndReportOnError foamCalc components U -case .. -time 2000
runApplicationAndReportOnError sample -case .. -time 2000
runApplicationAndReportOnError gnuplot compareAll.gplt    ; mv log.gnuplot log.gnuplotCompareAll
runApplicationAndReportOnError foamLog ../log.simpleFoam 
runApplicationAndReportOnError gnuplot plotResiduals.gplt ; mv log.gnuplot log.gnuplotPlotResiduals
